import { TAG_VARIANTS } from '@private/components';

export enum TRANSACTIONS_KEYS {
  ALL = 'transactions',
  TRANSACTION_DETAILS = 'transaction_details',
  TRANSACTION_CARD = 'transaction_card',
  TRANSACTION_CUSTOMER = 'transaction_customer',
  OPERATION_HISTORY = 'operation_history',
  WEBHOOKS = 'webhooks',
}

export enum TRANSACTIONS_TYPE {
  PURCHASE = 'PURCHASE',
  PAYOUT = 'PAYOUT',
  REFUND = 'REFUND',
}

export const TRANSACTIONS_TYPE_VARIANTS = {
  [TRANSACTIONS_TYPE.PURCHASE]: TAG_VARIANTS.SUCCESS,
  [TRANSACTIONS_TYPE.PAYOUT]: TAG_VARIANTS.WARNING,
  [TRANSACTIONS_TYPE.REFUND]: TAG_VARIANTS.ERROR,
};

export enum TRANSACTIONS_STATE {
  AUTHORIZED = 'AUTHORIZED',
  CANCELLED = 'CANCELLED',
  COMPLETED = 'COMPLETED',
  CREATED = 'CREATED',
  DECLINED = 'DECLINED',
  ERROR = 'ERROR',
  INVALID = 'INVALID',
  IN_PROGRESS = 'IN_PROGRESS',
  ON_HOLD = 'ON_HOLD',
  PARTIALLY_REFUNDED = 'PARTIALLY_REFUNDED',
  PENDING = 'PENDING',
  PENDING_AND_SEND_WEBHOOK = 'PENDING_AND_SEND_WEBHOOK',
  PENDING_CONFIRMATION_REQUIRED = 'PENDING_CONFIRMATION_REQUIRED',
  PENDING_INPUT_REQUIRED = 'PENDING_INPUT_REQUIRED',
  RECONCILIATION_REQUIRED = 'RECONCILIATION_REQUIRED',
  REFUNDED = 'REFUNDED',
  REFUND_REQUIRED = 'REFUND_REQUIRED',
  THREEDS_ENROLLED = 'THREEDS_ENROLLED',
  THREEDS_PASSED = 'THREEDS_PASSED',
  TIMEOUT = 'TIMEOUT',
  VOIDED = 'VOIDED',
  WAITING_FOR_WEBHOOK = 'WAITING_FOR_WEBHOOK',
}

export const TRANSACTIONS_STATE_VARIANTS: Record<string, string> = {
  [TRANSACTIONS_STATE.CANCELLED]: 'error',
  [TRANSACTIONS_STATE.DECLINED]: 'error',
  [TRANSACTIONS_STATE.ERROR]: 'error',
  [TRANSACTIONS_STATE.INVALID]: 'error',
  [TRANSACTIONS_STATE.TIMEOUT]: 'error',
  [TRANSACTIONS_STATE.COMPLETED]: 'success',
  [TRANSACTIONS_STATE.PARTIALLY_REFUNDED]: 'success',
  [TRANSACTIONS_STATE.REFUNDED]: 'success',
};

export enum OPERATION_STATE {
  COMPLETED = 'completed',
  CONFLICT = 'conflict',
  ERROR = 'error',
  IN_PROGRESS = 'in_progress',
}

export const OPERATION_STATE_TAG = {
  [OPERATION_STATE.COMPLETED]: TAG_VARIANTS.SUCCESS,
  [OPERATION_STATE.CONFLICT]: TAG_VARIANTS.WARNING,
  [OPERATION_STATE.ERROR]: TAG_VARIANTS.ERROR,
  [OPERATION_STATE.IN_PROGRESS]: TAG_VARIANTS.PRIMARY,
};

export enum TRANSACTION_STATUS {
  SUCCESS = 'SUCCESS',
  DECLINE = 'DECLINE',
  ANY = 'ANY',
}

export const TRANSACTION_STATUS_TAG = {
  [TRANSACTION_STATUS.SUCCESS]: TAG_VARIANTS.SUCCESS,
  [TRANSACTION_STATUS.DECLINE]: TAG_VARIANTS.ERROR,
  [TRANSACTION_STATUS.ANY]: TAG_VARIANTS.WARNING,
};

export const INITIAL_ON_COLUMNS_TRANSACTIONS = [
  'id',
  'merchantTerminalName',
  'amount',
  'currency',
  'state',
  'type',
  'created',
];
